name: Notebook Diff
on:
  pull_request:
    paths:
      - '*.ipynb'

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1

    - name: notebook-diff
      run: | 
        pip install -r requirements.txt
        ./diff.sh

        